# Generated by Django 6.0.5 on 2026-05-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_alternate_phone_user_employee_id_user_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joining_date',
            new_name='date_of_joining',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='alternate_phone',
            new_name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('RECRUITER', 'Recruiter'), ('HR', 'Hr'), ('JUNIOR_HR', 'Junior Hr')], max_length=20),
        ),
    ]
