# Generated by Django 6.0.5 on 2026-05-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_skill_jobrequest_approved_at_jobrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='skills_required',
            field=models.TextField(blank=True, help_text='Comma separated e.g. Python, Django, React'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='experience_required',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='vacancies',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
