# Generated by Django 6.0.5 on 2026-05-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobrequest_required_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='basic_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='key_responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='preferred_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
