# Generated by Django 6.0.5 on 2026-05-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
