# Generated by Django 6.0.5 on 2026-06-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_emaillog_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='fit_summary',
            field=models.TextField(blank=True),
        ),
    ]
