# Generated by Django 6.0.5 on 2026-06-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_candidateresume_fit_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateresume',
            name='resume',
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='resume_url',
            field=models.URLField(blank=True, help_text="Direct link to the candidate's resume", max_length=500),
        ),
    ]
