# Generated by Django 6.0.5 on 2026-06-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_remove_candidateresume_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
