# Generated by Django 6.0.5 on 2026-06-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_candidateresume_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_method', models.CharField(blank=True, max_length=50)),
                ('ollama_model', models.CharField(blank=True, max_length=50)),
                ('ollama_raw_output', models.TextField(blank=True)),
                ('extracted_name', models.CharField(blank=True, max_length=255)),
                ('extracted_email', models.CharField(blank=True, max_length=255)),
                ('extracted_phone', models.CharField(blank=True, max_length=50)),
                ('extracted_experience', models.FloatField(default=0.0)),
                ('extracted_skills', models.JSONField(default=list)),
                ('llm_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('OLLAMA_ERROR', 'Ollama Error'), ('ERROR', 'Error'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Resume Processing Log',
                'verbose_name_plural': 'Resume Processing Logs',
                'ordering': ['-processed_at'],
            },
        ),
    ]
