# Generated by Django 6.0.5 on 2026-06-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_resumeprocessinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
