# Generated by Django 6.0.5 on 2026-06-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_candidateresume_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='chroma_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='github_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
