# Generated by Django 6.0.5 on 2026-06-23 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobrequest_basic_qualifications_and_more'),
        ('recruitment', '0010_candidateresume_chroma_id_candidateresume_github_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateresume',
            name='fit_summary',
        ),
        migrations.RemoveField(
            model_name='candidateresume',
            name='is_shortlisted',
        ),
        migrations.RemoveField(
            model_name='candidateresume',
            name='job_request',
        ),
        migrations.RemoveField(
            model_name='candidateresume',
            name='match_percentage',
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ResumeScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_score', models.FloatField(default=0)),
                ('threshold_used', models.FloatField(default=70.0)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('fit_summary', models.TextField(blank=True)),
                ('matched_skills', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('ROUND_1', 'Round 1'), ('ROUND_2', 'Round 2'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='jobs.jobrequest')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='recruitment.candidateresume')),
                ('screened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-screened_at'],
                'unique_together': {('resume', 'job_request')},
            },
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.resumescreening'),
        ),
        migrations.DeleteModel(
            name='ShortlistedCandidate',
        ),
    ]
