# Generated by Django 6.0.5 on 2026-06-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_remove_candidateresume_fit_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='pushed_to_sharepoint',
            field=models.BooleanField(default=False),
        ),
    ]
